# Generated by Django 4.2.7 on 2023-12-01 17:13

import cliente.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('id_cliente_pf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[cliente.models.validate_cpf])),
                ('rg', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('id_cliente_pj', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('data_abertura', models.DateField()),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente_pf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pf_conta', to='cliente.clientepf')),
                ('cliente_pj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pj_conta', to='cliente.clientepj')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprovado', models.BooleanField(default=False)),
                ('numero_parcelas', models.IntegerField(blank=True)),
                ('data_aprovacao', models.DateField(blank=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoParcela',
            fields=[
                ('id_parcela', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=60)),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateTimeField(blank=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('fk_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('bandeira', models.CharField(max_length=20)),
                ('situacao', models.CharField(max_length=10)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
    ]
