# Generated by Django 4.2.7 on 2023-12-04 14:06

import cliente.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=80)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('id_cliente_pf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[cliente.models.validate_cpf])),
                ('rg', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('id_cliente_pj', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('data_abertura', models.DateField()),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente_pf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pf_conta', to='cliente.clientepf')),
                ('cliente_pj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pj_conta', to='cliente.clientepj')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprovado', models.BooleanField(default=False)),
                ('numero_parcelas', models.IntegerField(blank=True)),
                ('data_aprovacao', models.DateField(blank=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoParcela',
            fields=[
                ('id_parcela', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=60)),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateTimeField(blank=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('fk_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('bandeira', models.CharField(max_length=20)),
                ('situacao', models.CharField(max_length=10)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
    ]
