# Generated by Django 4.2.7 on 2023-11-29 13:19

import cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('id_cliente_pf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[cliente.models.validate_cpf])),
                ('rg', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('id_cliente_pj', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('data_abertura', models.DateField()),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=120)),
            ],
        ),
    ]
