# Generated by Django 4.2.7 on 2023-12-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='bandeira',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='fk_conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.conta'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='numero',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='situacao',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='validade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cliente_pf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pf_conta', to='cliente.clientepf'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cliente_pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pj_conta', to='cliente.clientepj'),
        ),
    ]
