# Generated by Django 4.2.7 on 2023-11-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprovado', models.BooleanField(default=False)),
                ('numero_parcelas', models.IntegerField(blank=True)),
                ('data_aprovacao', models.DateField(blank=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoParcela',
            fields=[
                ('id_parcela', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=60)),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateTimeField(blank=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('fk_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePJConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientepj')),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePFConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientepf')),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('bandeira', models.CharField(max_length=20)),
                ('situacao', models.CharField(max_length=10)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
    ]
