# Generated by Django 4.2.7 on 2023-12-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cartao_limite_alter_cartao_bandeira_alter_cartao_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_por_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='fk_conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.conta'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='juros',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_solicitado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='EmprestimoParcela',
        ),
    ]
