# Generated by Django 4.2.7 on 2023-12-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_emprestimo_aprovado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transferencia', models.CharField(max_length=30)),
                ('tipo_operacao', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('fk_conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
        migrations.DeleteModel(
            name='Transferencias',
        ),
    ]
